export enum Animation {
	None = 0,
	Blur = 1,
	Fade = 2,
	Fly = 3,
	FlyRandom = 4,
	FlyAutomatic = 5,
	Scale = 6,
	Slide = 7,
}

export enum AnimationTrigger {
	None = "None",
	Player1Percent = "Player1 Percent Increase",
	Player2Percent = "Player2 Percent Increase",
	Player1StockLost = "Player1 Stock Loss",
	Player2StockLost = "Player2 Stock Loss",
}

export enum AutoUpdaterStatus {
	DownloadAvailable = "Download",
	LookingForUpdate = "Looking For Update",
	Downloading = "Downloading",
	DownloadComplete = "Install",
	Installing = "Installing",
	UpToDate = "Up To Date"
}

export enum Character {
	Falcon = 0,
	DK = 1,
	Fox = 2,
	GW = 3,
	Kirby = 4,
	Bowser = 5,
	Link = 6,
	Luigi = 7,
	Mario = 8,
	Marth = 9,
	MewTwo = 10,
	Ness = 11,
	Peach = 12,
	Pikachu = 13,
	IceClimbers = 14,
	Jigglypuff = 15,
	Samus = 16,
	Yoshi = 17,
	Zelda = 18,
	Sheik = 19,
	Falco = 20,
	YoungLink = 21,
	DrMario = 22,
	Roy = 23,
	Pichu = 24,
	Ganondorf = 25
}

export enum DolphinConnectionState {
	Disconnected = "Disconnected",
	Connected = "Connected",
	Connecting = "Connecting",
	Searching = "Searching",
}

export enum Easing {
	None = 0,
	BackInOut = 1,
	BounceInOut = 2,
	BounceIn = 3,
	BounceOut = 4,
	ElasticInOut = 5,
	ElasticIn = 6,
	ElasticOut = 7,
	SineOut = 8
}

export enum ElementCategory {
	CustomUi = "Custom UI",
	Player1CustomUi = "Player1 Custom UI",
	Player2CustomUi = "Player2 Custom UI",
	CurrentPlayerPostGameAttackCount = "Current Player Attack Count",
	Player1PostGameAttackCount = "Player1 Attack Count",
	Player2PostGameAttackCount = "Player2 Attack Count",
	CurrentPlayerPostGameActionCount = "Current Player Action Count",
	Player1PostGameActionCount = "Player1 Action Count",
	Player2PostGameActionCount = "Player2 Action Count",
	CurrentPlayerPostGameOverallStats = "Current Player Overall Stats",
	Player1PostGameOverallStats = "Player1 Overall Stats",
	Player2PostGameOverallStats = "Player2 Overall Stats",
	PostSetStats = "Post Set Stats",
	CurrentSetStats = "Current Set Stats",
	Custom = "Custom",
	CurrentPlayerSlippiData = "Current Player Slippi Data",
	Player1SlippiData = "Player1 Slippi Data",
	Player2SlippiData = "Player2 Slippi Data",
	ControllerInput = "Controller Input",
}

export enum ElementVisibilityOption {
	Always = "Always",
	GameRunning = "GameRunning",
	GamePaused = "GamePaused",
}

export enum InGameState {
	Inactive = "Inactive",
	Running = "Running",
	Paused = "Paused",
}

export enum LiveStatsScene {
	WaitingForDolphin = "Waiting",
	Menu = "Menu",
	InGame = "In Game",
	PostGame = "Post Game",
	PostSet = "Post Set",
	RankChange = "Rank Change",
}

export enum PlayerActionState {
	Dead = 0
}

export enum SceneBackground {
	None = "None",
	Color = "Color",
	Image = "Image",
	ImageCustom = "Custom Image",
	InGameImageStage = "In Game Stage Image",
	PostGameImageStage = "Post Game Stage Image",
}

export enum Transition {
	None = 0,
	Fade = 1,
	Scale = 2,
	Fly = 3,
	Slide = 4,
	Blur = 5,
	Draw = 6,
	CrossFade = 7,
}

export enum CustomElement {

	// Custom String
	CustomString = 1000,
	InGameCurrentPlayerPercent = 1001,
	InGamePlayer1Percent = 1002,
	InGamePlayer2Percent = 1003,
	InGameCurrentPlayerPercentDecimal = 1004,
	InGamePlayer1PercentDecimal = 1005,
	InGamePlayer2PercentDecimal = 1006,

	// Custom Image
	CustomImage = 2000,
	InGameCurrentPlayerCharacterRender = 2001,
	InGamePlayer1CharacterRender = 2002,
	InGamePlayer2CharacterRender = 2003,

	// Custom Box
	CustomBox = 3000,

	// String
	// Rank Data
	SlippiRankCurrentPlayerTag = 4000,
	SlippiRankPlayer1Tag = 4001,
	SlippiRankPlayer2Tag = 4002,
	SlippiRankCurrentPlayerScore = 4003,
	SlippiRankCurrentPlayerRankText = 4006,
	SlippiRankPlayer1RankText = 4007,
	SlippiRankPlayer2RankText = 4008,
	SlippiRankCurrentPlayerRating = 4009,
	SlippiRankPlayer1Rating = 4010,
	SlippiRankPlayer2Rating = 4011,
	SlippiRankCurrentPlayerConnectCode = 4012,
	SlippiRankPlayer1ConnectCode = 4013,
	SlippiRankPlayer2ConnectCode = 40140,
	SlippiRankCurrentPlayerContinent = 4015,
	SlippiRankPlayer1Continent = 4016,
	SlippiRankPlayer2Continent = 4017,
	SlippiRankCurrentPlayerContinentInitials = 4018,
	SlippiRankPlayer1ContinentInitials = 4019,
	SlippiRankPlayer2ContinentInitials = 4020,
	SlippiRankCurrentPlayerDailyGlobalPlacement = 4100,
	SlippiRankPlayer1DailyGlobalPlacement = 4101,
	SlippiRankPlayer2DailyGlobalPlacement = 4102,
	SlippiRankCurrentPlayerDailyRegionalPlacement = 4103,
	SlippiRankPlayer1DailyRegionalPlacement = 4104,
	SlippiRankPlayer2DailyRegionalPlacement = 4105,
	SlippiRankCurrentPlayerWins = 4106,
	SlippiRankPlayer1Wins = 4107,
	SlippiRankPlayer2Wins = 4108,
	SlippiRankCurrentPlayerWinsPercent = 4109,
	SlippiRankPlayer1WinsPercent = 4110,
	SlippiRankPlayer2WinsPercent = 4111,
	SlippiRankCurrentPlayerLosses = 4112,
	SlippiRankPlayer1Losses = 4113,
	SlippiRankPlayer2Losses = 4114,
	SlippiRankCurrentPlayerLossesPercent = 4115,
	SlippiRankPlayer1LossesPercent = 4116,
	SlippiRankPlayer2LossesPercent = 4117,
	SlippiRankCurrentPlayerCharacter1 = 4118,
	SlippiRankPlayer1Character1 = 4119,
	SlippiRankPlayer2Character1 = 4120,
	SlippiRankCurrentPlayerCharacter2 = 4121,
	SlippiRankPlayer1Character2 = 4122,
	SlippiRankPlayer2Character2 = 4123,
	SlippiRankCurrentPlayerCharacter3 = 4124,
	SlippiRankPlayer1Character3 = 4125,
	SlippiRankPlayer2Character3 = 4126,
	SlippiRankCurrentPlayerCharacter1Percent = 4127,
	SlippiRankPlayer1Character1Percent = 4128,
	SlippiRankPlayer2Character1Percent = 4129,
	SlippiRankCurrentPlayerCharacter2Percent = 4130,
	SlippiRankPlayer1Character2Percent = 4131,
	SlippiRankPlayer2Character2Percent = 4132,
	SlippiRankCurrentPlayerCharacter3Percent = 4133,
	SlippiRankPlayer1Character3Percent = 4134,
	SlippiRankPlayer2Character3Percent = 4135,

	// In Game
	InGamePlayer1Score = 4200,
	InGamePlayer2Score = 4201,

	// Post Game
	PostGameCurrentPlayerAttackCountBair = 4400,
	PostGamePlayer1AttackCountBair = 4401,
	PostGamePlayer2AttackCountBair = 4402,
	PostGameCurrentPlayerAttackCountDair = 4403,
	PostGamePlayer1AttackCountDair = 4404,
	PostGamePlayer2AttackCountDair = 4405,
	PostGameCurrentPlayerAttackCountDash = 4406,
	PostGamePlayer1AttackCountDash = 4407,
	PostGamePlayer2AttackCountDash = 4408,
	PostGameCurrentPlayerAttackCountDsmash = 4409,
	PostGamePlayer1AttackCountDsmash = 4410,
	PostGamePlayer2AttackCountDsmash = 4411,
	PostGameCurrentPlayerAttackCountDtilt = 4412,
	PostGamePlayer1AttackCountDtilt = 4413,
	PostGamePlayer2AttackCountDtilt = 4414,
	PostGameCurrentPlayerAttackCountFair = 4415,
	PostGamePlayer1AttackCountFair = 4416,
	PostGamePlayer2AttackCountFair = 4417,
	PostGameCurrentPlayerAttackCountFsmash = 4418,
	PostGamePlayer1AttackCountFsmash = 4419,
	PostGamePlayer2AttackCountFsmash = 4420,
	PostGameCurrentPlayerAttackCountFtilt = 4421,
	PostGamePlayer1AttackCountFtilt = 4422,
	PostGamePlayer2AttackCountFtilt = 4423,
	PostGameCurrentPlayerAttackCountJab = 4424,
	PostGamePlayer1AttackCountJab = 4425,
	PostGamePlayer2AttackCountJab = 4426,
	PostGameCurrentPlayerAttackCountJab2 = 4427,
	PostGamePlayer1AttackCountJab2 = 4428,
	PostGamePlayer2AttackCountJab2 = 4429,
	PostGameCurrentPlayerAttackCountJab3 = 4430,
	PostGamePlayer1AttackCountJab3 = 4431,
	PostGamePlayer2AttackCountJab3 = 4432,
	PostGameCurrentPlayerAttackCountJabMulti = 4433,
	PostGamePlayer1AttackCountJabMulti = 4434,
	PostGamePlayer2AttackCountJabMulti = 4435,
	PostGameCurrentPlayerAttackCountNair = 4436,
	PostGamePlayer1AttackCountNair = 4437,
	PostGamePlayer2AttackCountNair = 4438,
	PostGameCurrentPlayerAttackCountUair = 4439,
	PostGamePlayer1AttackCountUair = 4440,
	PostGamePlayer2AttackCountUair = 4441,
	PostGameCurrentPlayerAttackCountUsmash = 4442,
	PostGamePlayer1AttackCountUsmash = 4443,
	PostGamePlayer2AttackCountUsmash = 4444,
	PostGameCurrentPlayerAttackCountUtilt = 4445,
	PostGamePlayer1AttackCountUtilt = 4446,
	PostGamePlayer2AttackCountUtilt = 4447,

	PostGameCurrentPlayerActionCountAirDodge = 4448,
	PostGamePlayer1ActionCountAirDodge = 4449,
	PostGamePlayer2ActionCountAirDodge = 4450,
	PostGameCurrentPlayerActionCountDashDance = 4451,
	PostGamePlayer1ActionCountDashDance = 4452,
	PostGamePlayer2ActionCountDashDance = 4453,
	PostGameCurrentPlayerActionCountLedgeGrab = 4454,
	PostGamePlayer1ActionCountLedgeGrab = 4455,
	PostGamePlayer2ActionCountLedgeGrab = 4456,
	PostGameCurrentPlayerActionCountRoll = 4457,
	PostGamePlayer1ActionCountRoll = 4458,
	PostGamePlayer2ActionCountRoll = 4459,
	PostGameCurrentPlayerActionCountSpotDodge = 4460,
	PostGamePlayer1ActionCountSpotDodge = 4461,
	PostGamePlayer2ActionCountSpotDodge = 4462,
	PostGameCurrentPlayerActionCountWaveDash = 4463,
	PostGamePlayer1ActionCountWaveDash = 4464,
	PostGamePlayer2ActionCountWaveDash = 4465,
	PostGameCurrentPlayerActionCountWaveLand = 4466,
	PostGamePlayer1ActionCountWaveLand = 4467,
	PostGamePlayer2ActionCountWaveLand = 4468,

	PostGameCurrentPlayerActionCountGrabTotal = 4469,
	PostGamePlayer1ActionCountGrabTotal = 4470,
	PostGamePlayer2ActionCountGrabTotal = 4471,
	PostGameCurrentPlayerActionCountGrabSuccess = 4472,
	PostGamePlayer1ActionCountGrabSuccess = 4473,
	PostGamePlayer2ActionCountGrabSuccess = 4474,
	PostGameCurrentPlayerActionCountGrabFail = 4475,
	PostGamePlayer1ActionCountGrabFail = 4476,
	PostGamePlayer2ActionCountGrabFail = 4477,
	PostGameCurrentPlayerActionCountGrabSuccessPercent = 4478,
	PostGamePlayer1ActionCountGrabSuccessPercent = 4479,
	PostGamePlayer2ActionCountGrabSuccessPercent = 4480,
	PostGameCurrentPlayerActionCountGrabFailPercent = 4481,
	PostGamePlayer1ActionCountGrabFailPercent = 4482,
	PostGamePlayer2ActionCountGrabFailPercent = 4483,

	PostGameCurrentPlayerActionCountGroundTechTotal = 4484,
	PostGamePlayer1ActionCountGroundTechTotal = 4485,
	PostGamePlayer2ActionCountGroundTechTotal = 4486,
	PostGameCurrentPlayerActionCountGroundTechIn = 4487,
	PostGamePlayer1ActionCountGroundTechIn = 4488,
	PostGamePlayer2ActionCountGroundTechIn = 4489,
	PostGameCurrentPlayerActionCountGroundTechAway = 4490,
	PostGamePlayer1ActionCountGroundTechAway = 4491,
	PostGamePlayer2ActionCountGroundTechAway = 4492,
	PostGameCurrentPlayerActionCountGroundTechNeutral = 4493,
	PostGamePlayer1ActionCountGroundTechNeutral = 4494,
	PostGamePlayer2ActionCountGroundTechNeutral = 4495,
	PostGameCurrentPlayerActionCountGroundTechSuccess = 4496,
	PostGamePlayer1ActionCountGroundTechSuccess = 4497,
	PostGamePlayer2ActionCountGroundTechSuccess = 4498,
	PostGameCurrentPlayerActionCountGroundTechSuccessPercent = 4499,
	PostGamePlayer1ActionCountGroundTechSuccessPercent = 4500,
	PostGamePlayer2ActionCountGroundTechSuccessPercent = 4501,
	PostGameCurrentPlayerActionCountGroundTechFail = 4502,
	PostGamePlayer1ActionCountGroundTechFail = 4503,
	PostGamePlayer2ActionCountGroundTechFail = 4504,
	PostGameCurrentPlayerActionCountGroundTechFailPercent = 4505,
	PostGamePlayer1ActionCountGroundTechFailPercent = 4506,
	PostGamePlayer2ActionCountGroundTechFailPercent = 4507,

	PostGameCurrentPlayerActionCountWallTechTotal = 4508,
	PostGamePlayer1ActionCountWallTechTotal = 4509,
	PostGamePlayer2ActionCountWallTechTotal = 4510,
	PostGameCurrentPlayerActionCountWallTechSuccess = 4511,
	PostGamePlayer1ActionCountWallTechSuccess = 4512,
	PostGamePlayer2ActionCountWallTechSuccess = 4513,
	PostGameCurrentPlayerActionCountWallTechFail = 4514,
	PostGamePlayer1ActionCountWallTechFail = 4515,
	PostGamePlayer2ActionCountWallTechFail = 4516,
	PostGameCurrentPlayerActionCountWallTechSuccessPercent = 4517,
	PostGamePlayer1ActionCountWallTechSuccessPercent = 4518,
	PostGamePlayer2ActionCountWallTechSuccessPercent = 4519,
	PostGameCurrentPlayerActionCountWallTechFailPercent = 4520,
	PostGamePlayer1ActionCountWallTechFailPercent = 4521,
	PostGamePlayer2ActionCountWallTechFailPercent = 4522,

	PostGameCurrentPlayerActionCountLCancelTotal = 4523,
	PostGamePlayer1ActionCountLCancelTotal = 4524,
	PostGamePlayer2ActionCountLCancelTotal = 4525,
	PostGameCurrentPlayerActionCountLCancelSuccess = 4526,
	PostGamePlayer1ActionCountLCancelSuccess = 4527,
	PostGamePlayer2ActionCountLCancelSuccess = 4528,
	PostGameCurrentPlayerActionCountLCancelFail = 4529,
	PostGamePlayer1ActionCountLCancelFail = 4530,
	PostGamePlayer2ActionCountLCancelFail = 4531,
	PostGameCurrentPlayerActionCountLCancelSuccessPercent = 4532,
	PostGamePlayer1ActionCountLCancelSuccessPercent = 4533,
	PostGamePlayer2ActionCountLCancelSuccessPercent = 4534,
	PostGameCurrentPlayerActionCountLCancelFailPercent = 4535,
	PostGamePlayer1ActionCountLCancelFailPercent = 4536,
	PostGamePlayer2ActionCountLCancelFailPercent = 4537,

	PostGameCurrentPlayerActionCountThrowTotal = 4538,
	PostGamePlayer1ActionCountThrowTotal = 4539,
	PostGamePlayer2ActionCountThrowTotal = 4540,
	PostGameCurrentPlayerActionCountThrowUp = 4541,
	PostGamePlayer1ActionCountThrowUp = 4542,
	PostGamePlayer2ActionCountThrowUp = 4543,
	PostGameCurrentPlayerActionCountThrowForward = 4544,
	PostGamePlayer1ActionCountThrowForward = 4545,
	PostGamePlayer2ActionCountThrowForward = 4546,
	PostGameCurrentPlayerActionCountThrowBack = 4547,
	PostGamePlayer1ActionCountThrowBack = 4548,
	PostGamePlayer2ActionCountThrowBack = 4549,
	PostGameCurrentPlayerActionCountThrowDown = 4550,
	PostGamePlayer1ActionCountThrowDown = 4551,
	PostGamePlayer2ActionCountThrowDown = 4552,

	PostGameOverallBeneficialTradeTotal = 4553,
	PostGameCurrentPlayerOverallBeneficialTradeCount = 4554,
	PostGamePlayer1OverallBeneficialTradeCount = 4555,
	PostGamePlayer2OverallBeneficialTradeCount = 4556,
	PostGameCurrentPlayerOverallBeneficialTradeRatio = 4557,
	PostGamePlayer1OverallBeneficialTradeRatio = 4558,
	PostGamePlayer2OverallBeneficialTradeRatio = 4559,
	PostGameOverallCounterHitTotal = 4560,
	PostGameCurrentPlayerOverallCounterHitCount = 4563,
	PostGamePlayer1OverallCounterHitCount = 4564,
	PostGamePlayer2OverallCounterHitCount = 4565,
	PostGameCurrentPlayerOverallCounterHitRatio = 4566,
	PostGamePlayer1OverallCounterHitRatio = 4567,
	PostGamePlayer2OverallCounterHitRatio = 4568,
	PostGameCurrentPlayerOverallDamageTotal = 4569,
	PostGamePlayer1OverallDamageTotal = 4570,
	PostGamePlayer2OverallDamageTotal = 4571,
	PostGameCurrentPlayerOverallOpeningsTotal = 4572,
	PostGamePlayer1OverallOpeningsTotal = 4573,
	PostGamePlayer2OverallOpeningsTotal = 4574,
	PostGameCurrentPlayerOverallDamagePerOpening = 4575,
	PostGamePlayer1OverallDamagePerOpening = 4576,
	PostGamePlayer2OverallDamagePerOpening = 4577,
	PostGameCurrentPlayerOverallDigitalInputsTotal = 4578,
	PostGamePlayer1OverallDigitalInputsTotal = 4579,
	PostGamePlayer2OverallDigitalInputsTotal = 4580,
	PostGameCurrentPlayerOverallDigitalInputsPerMinute = 4580,
	PostGamePlayer1OverallDigitalInputsPerMinute = 4581,
	PostGamePlayer2OverallDigitalInputsPerMinute = 4582,
	PostGameCurrentPlayerOverallDigitalInputsPerSecond = 4583,
	PostGamePlayer1OverallDigitalInputsPerSecond = 4584,
	PostGamePlayer2OverallDigitalInputsPerSecond = 4585,
	PostGameCurrentPlayerOverallInputsTotal = 4586,
	PostGamePlayer1OverallInputsTotal = 4587,
	PostGamePlayer2OverallInputsTotal = 4588,
	PostGameCurrentPlayerOverallInputsPerMinute = 4589,
	PostGamePlayer1OverallInputsPerMinute = 4590,
	PostGamePlayer2OverallInputsPerMinute = 4591,
	PostGameCurrentPlayerOverallInputsPerSecond = 4592,
	PostGamePlayer1OverallInputsPerSecond = 4593,
	PostGamePlayer2OverallInputsPerSecond = 4594,
	PostGameOverallNeutralWinsTotal = 4595,
	PostGameCurrentPlayerOverallNeutralWinsCount = 4596,
	PostGamePlayer1OverallNeutralWinsCount = 4597,
	PostGamePlayer2OverallNeutralWinsCount = 4598,
	PostGameCurrentPlayerOverallNeutralWinsRatio = 4599,
	PostGamePlayer1OverallNeutralWinsRatio = 4600,
	PostGamePlayer2OverallNeutralWinsRatio = 4601,
	PostGameCurrentPlayerOverallOpeningsPerKill = 4602,
	PostGamePlayer1OverallOpeningsPerKill = 4603,
	PostGamePlayer2OverallOpeningsPerKill = 4604,

	PostGameCurrentPlayerOverallStocksRemaining = 4605,
	PostGamePlayer1OverallStocksRemaining = 4606,
	PostGamePlayer2OverallStocksRemaining = 4607,


	// Post Set
	// 5000-5399

	// Set
	CurrentSetGameMode = 5400,
	CurrentSetGameBestOf = 5401,
	CurrentSetPlayer1Score = 5402,
	CurrentSetPlayer2Score = 5403,

	CurrentSetGame1Player1Score = 5410,
	CurrentSetGame1Player2Score = 5411,
	CurrentSetGame1Player1StocksRemaining = 5412,
	CurrentSetGame1Player2StocksRemaining = 5413,

	CurrentSetGame2Player1Score = 5420,
	CurrentSetGame2Player2Score = 5421,
	CurrentSetGame2Player1StocksRemaining = 5422,
	CurrentSetGame2Player2StocksRemaining = 5423,

	CurrentSetGame3Player1Score = 5430,
	CurrentSetGame3Player2Score = 5431,
	CurrentSetGame3Player1StocksRemaining = 5432,
	CurrentSetGame3Player2StocksRemaining = 5433,

	CurrentSetGame4Player1Score = 5440,
	CurrentSetGame4Player2Score = 5441,
	CurrentSetGame4Player1StocksRemaining = 5442,
	CurrentSetGame4Player2StocksRemaining = 5443,

	CurrentSetGame5Player1Score = 5450,
	CurrentSetGame5Player2Score = 5451,
	CurrentSetGame5Player1StocksRemaining = 5452,
	CurrentSetGame5Player2StocksRemaining = 5453,

	// Session

	// Image
	// Rank Data
	SlippiRankCurrentPlayerRankIcon = 6000,
	SlippiRankPlayer1RankIcon = 6001,
	SlippiRankPlayer2RankIcon = 6002,
	SlippiRankCurrentPlayerCharacterIcon = 6003,
	SlippiRankPlayer1CharacterIcon = 6004,
	SlippiRankPlayer2CharacterIcon = 6005,
	SlippiRankCurrentPlayerCharacter1Icon = 6006,
	SlippiRankPlayer1Character1Icon = 6007,
	SlippiRankPlayer2Character1Icon = 6008,
	SlippiRankCurrentPlayerCharacter2Icon = 6009,
	SlippiRankPlayer1Character2Icon = 6010,
	SlippiRankPlayer2Character2Icon = 6011,
	SlippiRankCurrentPlayerCharacter3Icon = 6012,
	SlippiRankPlayer1Character3Icon = 6013,
	SlippiRankPlayer2Character3Icon = 6014,

	// In Game
	InGameStage = 6200,
	InGamePlayer1CharacterIcon = 6202,
	InGamePlayer2CharacterIcon = 6203,

	// Post Game
	PostGameStage = 6300,
	PostGameCurrentPlayerCharacterIcon = 6301,
	PostGamePlayer1CharacterIcon = 6302,
	PostGamePlayer2CharacterIcon = 6303,
	PostGameCurrentPlayerCharacterRender = 6304,
	PostGamePlayer1CharacterRender = 6305,
	PostGamePlayer2CharacterRender = 6306,

	// Post Set

	// Current Set
	CurrentSetGame1Stage = 6310,
	CurrentSetGame1Player1CharacterIcon = 6311,
	CurrentSetGame1Player2CharacterIcon = 6312,
	CurrentSetGame1Player1CharacterRender = 6313,
	CurrentSetGame1Player2CharacterRender = 6314,

	CurrentSetGame2Stage = 6320,
	CurrentSetGame2Player1CharacterIcon = 6321,
	CurrentSetGame2Player2CharacterIcon = 6322,
	CurrentSetGame2Player1CharacterRender = 6323,
	CurrentSetGame2Player2CharacterRender = 6324,

	CurrentSetGame3Stage = 6330,
	CurrentSetGame3Player1CharacterIcon = 6331,
	CurrentSetGame3Player2CharacterIcon = 6332,
	CurrentSetGame3Player1CharacterRender = 6333,
	CurrentSetGame3Player2CharacterRender = 6334,

	CurrentSetGame4Stage = 6340,
	CurrentSetGame4Player1CharacterIcon = 6341,
	CurrentSetGame4Player2CharacterIcon = 6342,
	CurrentSetGame4Player1CharacterRender = 6343,
	CurrentSetGame4Player2CharacterRender = 6344,

	CurrentSetGame5Stage = 6350,
	CurrentSetGame5Player1CharacterIcon = 6351,
	CurrentSetGame5Player2CharacterIcon = 6352,
	CurrentSetGame5Player1CharacterRender = 6353,
	CurrentSetGame5Player2CharacterRender = 6354,
}