import type { StageData } from "../types/slippiData";

export const STAGE_DATA: { [stageId: number]: StageData } = {
    2: {
        name: "Fountain of Dreams",
        leftXBoundary: -198.75,
        rightXBoundary: 198.75,
        upperYBoundary: 202.5,
        lowerYBoundary: -146.25,
        mainPlatformHeight: 0, // grassy sides are raised at 0.6214
        sidePlatformHeight: 27.375, // moves up and down
        topPlatformHeight: 42.75,
        leftLedgeX: -63.35,
        rightLedgeX: 63.35,
    },
    3: {
        name: "Pokemon Stadium", // transforms, no top
        leftXBoundary: -230,
        rightXBoundary: 230,
        upperYBoundary: 180,
        lowerYBoundary: -111,
        mainPlatformHeight: 0, // just a good guess
        sidePlatformHeight: 25,
        leftLedgeX: -87.75,
        rightLedgeX: 87.75,
    },
    8: {
        name: "Yoshi's Story",
        leftXBoundary: -175.7,
        rightXBoundary: 173.6,
        upperYBoundary: 168,
        lowerYBoundary: -91,
        mainPlatformHeight: 0, // has slopes
        sidePlatformHeight: 23.45,
        topPlatformHeight: 42,
        leftLedgeX: -56,
        rightLedgeX: 56,
    },
    28: {
        name: "Dream Land N64",
        leftXBoundary: -255,
        rightXBoundary: 255,
        upperYBoundary: 250,
        lowerYBoundary: -123,
        mainPlatformHeight: 0.01,
        sidePlatformHeight: 30.2425,
        topPlatformHeight: 51.4264,
        leftLedgeX: -77.27,
        rightLedgeX: 77.27,
    },
    31: {
        name: "Battlefield",
        leftXBoundary: -224,
        rightXBoundary: 224,
        upperYBoundary: 200,
        lowerYBoundary: -108.8,
        mainPlatformHeight: 0,
        sidePlatformHeight: 27.2,
        topPlatformHeight: 54.4,
        leftLedgeX: -68.4,
        rightLedgeX: 68.4,
    },
    32: {
        name: "Final Destination", // no side/top
        leftXBoundary: -246,
        rightXBoundary: 246,
        upperYBoundary: 188,
        lowerYBoundary: -140,
        mainPlatformHeight: 0,
        leftLedgeX: -85.5606,
        rightLedgeX: 85.5606,
    },
};

export enum Stage {
    FOUNTAIN_OF_DREAMS = 2,
    POKEMON_STADIUM = 3,
    PEACHS_CASTLE = 4,
    KONGO_JUNGLE = 5,
    BRINSTAR = 6,
    CORNERIA = 7,
    YOSHIS_STORY = 8,
    ONETT = 9,
    MUTE_CITY = 10,
    RAINBOW_CRUISE = 11,
    JUNGLE_JAPES = 12,
    GREAT_BAY = 13,
    HYRULE_TEMPLE = 14,
    BRINSTAR_DEPTHS = 15,
    YOSHIS_ISLAND = 16,
    GREEN_GREENS = 17,
    FOURSIDE = 18,
    MUSHROOM_KINGDOM = 19,
    MUSHROOM_KINGDOM_2 = 20,
    VENOM = 22,
    POKE_FLOATS = 23,
    BIG_BLUE = 24,
    ICICLE_MOUNTAIN = 25,
    ICETOP = 26,
    FLAT_ZONE = 27,
    DREAMLAND = 28,
    YOSHIS_ISLAND_N64 = 29,
    KONGO_JUNGLE_N64 = 30,
    BATTLEFIELD = 31,
    FINAL_DESTINATION = 32,
    TARGET_TEST_MARIO = 33,
    TARGET_TEST_CAPTAIN_FALCON = 34,
    TARGET_TEST_YOUNG_LINK = 35,
    TARGET_TEST_DONKEY_KONG = 36,
    TARGET_TEST_DR_MARIO = 37,
    TARGET_TEST_FALCO = 38,
    TARGET_TEST_FOX = 39,
    TARGET_TEST_ICE_CLIMBERS = 40,
    TARGET_TEST_KIRBY = 41,
    TARGET_TEST_BOWSER = 42,
    TARGET_TEST_LINK = 43,
    TARGET_TEST_LUIGI = 44,
    TARGET_TEST_MARTH = 45,
    TARGET_TEST_MEWTWO = 46,
    TARGET_TEST_NESS = 47,
    TARGET_TEST_PEACH = 48,
    TARGET_TEST_PICHU = 49,
    TARGET_TEST_PIKACHU = 50,
    TARGET_TEST_JIGGLYPUFF = 51,
    TARGET_TEST_SAMUS = 52,
    TARGET_TEST_SHEIK = 53,
    TARGET_TEST_YOSHI = 54,
    TARGET_TEST_ZELDA = 55,
    TARGET_TEST_GAME_AND_WATCH = 56,
    TARGET_TEST_ROY = 57,
    TARGET_TEST_GANONDORF = 58,
    RACE_TO_THE_FINISH = 82,
    GRAB_THE_TROPHIES = 83,
    HOME_RUN_CONTEST = 84,
    ALL_STAR_LOBBY = 85,
    EVENT_ONE = 202,
    EVENT_EIGHTEEN = 203,
    EVENT_THREE = 204,
    EVENT_FOUR = 205,
    EVENT_FIVE = 206,
    EVENT_SIX = 207,
    EVENT_SEVEN = 208,
    EVENT_EIGHT = 209,
    EVENT_NINE = 210,
    EVENT_TEN_PART_ONE = 211,
    EVENT_ELEVEN = 212,
    EVENT_TWELVE = 213,
    EVENT_THIRTEEN = 214,
    EVENT_FOURTEEN = 215,
    EVENT_THIRTY_SEVEN = 216,
    EVENT_SIXTEEN = 217,
    EVENT_SEVENTEEN = 218,
    EVENT_TWO = 219,
    EVENT_NINETEEN = 220,
    EVENT_TWENTY_PART_ONE = 221,
    EVENT_TWENTY_ONE = 222,
    EVENT_TWENTY_TWO = 223,
    EVENT_TWENTY_SEVEN = 224,
    EVENT_TWENTY_FOUR = 225,
    EVENT_TWENTY_FIVE = 226,
    EVENT_TWENTY_SIX = 227,
    EVENT_TWENTY_THREE = 228,
    EVENT_TWENTY_EIGHT = 229,
    EVENT_TWENTY_NINE = 230,
    EVENT_THIRTY_PART_ONE = 231,
    EVENT_THIRTY_ONE = 232,
    EVENT_THIRTY_TWO = 233,
    EVENT_THIRTY_THREE = 234,
    EVENT_THIRTY_FOUR = 235,
    EVENT_FORTY_EIGHT = 236,
    EVENT_THIRTY_SIX_PART_ONE = 237,
    EVENT_FIFTEEN = 238,
    EVENT_THIRTY_EIGHT = 239,
    EVENT_THIRTY_NINE = 240,
    EVENT_FORTY_PART_ONE = 241,
    EVENT_FORTY_ONE = 242,
    EVENT_FORTY_TWO = 243,
    EVENT_FORTY_THREE = 244,
    EVENT_FORTY_FOUR = 245,
    EVENT_FORTY_FIVE = 246,
    EVENT_FORTY_SIX = 247,
    EVENT_FORTY_SEVEN = 248,
    EVENT_THIRTY_FIVE = 249,
    EVENT_FORTY_NINE_PART_ONE = 250,
    EVENT_FIFTY = 251,
    EVENT_FIFTY_ONE = 252,
    EVENT_TEN_PART_TWO = 253,
    EVENT_TEN_PART_THREE = 254,
    EVENT_TEN_PART_FOUR = 255,
    EVENT_TEN_PART_FIVE = 256,
    EVENT_TWENTY_PART_TWO = 257,
    EVENT_TWENTY_PART_THREE = 258,
    EVENT_TWENTY_PART_FOUR = 259,
    EVENT_TWENTY_PART_FIVE = 260,
    EVENT_THIRTY_PART_TWO = 261,
    EVENT_THIRTY_PART_THREE = 262,
    EVENT_THIRTY_PART_FOUR = 263,
    EVENT_FORTY_PART_TWO = 264,
    EVENT_FORTY_PART_THREE = 265,
    EVENT_FORTY_PART_FOUR = 266,
    EVENT_FORTY_PART_FIVE = 267,
    EVENT_FORTY_NINE_PART_TWO = 268,
    EVENT_FORTY_NINE_PART_THREE = 269,
    EVENT_FORTY_NINE_PART_FOUR = 270,
    EVENT_FORTY_NINE_PART_FIVE = 271,
    EVENT_FORTY_NINE_PART_SIX = 272,
    EVENT_THIRTY_SIX_PART_TWO = 273,
    MULTI_MAN_MELEE = 285
}